### ISSUE TITLE
Prevent achievement grinding through multiple characters

### ISSUE THREAD

**Issue by luttje** [luttje/gmod-experiment-redux#23]
Right now you can generate 5000 bolts quickly by:
1. Create character
2. Somehow get 1 bolt
3. Somehow die and lose the bolt
4. Get 5000 bolts for Boltless Wanderer
5. Move the bolts to another character somehow
6. Delete character, go back to step 1

I'm thinking of 2 possible ways to solve this:
- [x] Disable the ability to have multiple characters
- [x] Make achievements per-player instead of per-character

Although the latter is easier to implement, I'm thinking of also limiting the ability to create multiple characters. This because with the seasons and leaderboards I have in mind, it would be counter-productive to manage multiple characters anyway. 
Additionally it would improve the new/returning-player experience by reducing the amount of clicks they have to make ('New Characer'/'Load Character').

I'll probably solve it both ways, so if we reactivate multiple characters in the future, this exploit is fixed.

**Comment by utaysi** [comment]
While I think achieving the 2nd option is easy by tracking that specific achievement per user rather than per character (it would be achieved on all their characters after they achieve it once), I also can't think of many pros of keeping multiple characters. I can think of:

- You could have different characters in separate clans. 
- You could have one character with good, and one with bad karma for different perk sets. 
- Admin accounts to show people admins don't exploit their access on their RP accounts (which is just a facade that doesn't prove anything lol)
- Different characters for different RP personalities.
- Character for extra locker storage beyond tardis upgrade. 

I don't think these are such big use cases so getting rid of multiple characters would be okay if it improves general user experience with seemless logging in and simplicity.
